package autocode

type ServiceGroup struct {
	// Code generated by github.com/779789571/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	CollectorService
	ApiTokenService
	RequiredInfoService
	RulesService
	// Code generated by github.com/779789571/gin-vue-admin/server End; DO NOT EDIT.
}
