package autocode

type ApiGroup struct {
	// Code generated by github.com/779789571/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	CollectorApi
	ApiTokenApi
	RequiredInfoApi
	RulesApi
	// Code generated by github.com/779789571/gin-vue-admin/server End; DO NOT EDIT.
}
