package autocode

type RouterGroup struct {
	// Code generated by github.com/779789571/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	CollectorRouter
	ApiTokenRouter
	RequiredInfoRouter
	RulesRouter
	// Code generated by github.com/779789571/gin-vue-admin/server End; DO NOT EDIT.
}
